[package]
name = "flexc-redis"
version = "0.1.0"
authors = ["Wspsxing <biluohc@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
async-channel = "1.6"
tokio = { version = "0.2", features = [ "full" ] }

[dependencies]
flexc = { path = "../" }
redis = { version = "0.17", default-features = false, features = [ "tokio-comp" ] }
